"""
AI service layer for Virtelon Command Centre.

Modular abstraction over an LLM provider. Currently wired to Anthropic Claude
Sonnet 4.6 via the Emergent LLM key. Every public function degrades gracefully
to a clearly-marked heuristic result if the model call fails, so the product
never breaks. Nothing here fabricates contact details.
"""
import os
import json
import logging
from emergentintegrations.llm.chat import LlmChat, UserMessage

logger = logging.getLogger(__name__)

MODEL_PROVIDER = "anthropic"
MODEL_NAME = "claude-sonnet-4-6"

SYSTEM_PROMPT = (
    "You are Virtelon Intelligence, the analyst engine for Virtelon Pvt. Ltd., "
    "a software agency that builds custom software, CRM, ERP, AI chatbots/agents, "
    "automation, dashboards, web & mobile apps and SaaS. You assess business "
    "prospects for software-services opportunities. Be precise and honest. "
    "NEVER fabricate phone numbers, emails or private data. If something is not "
    "provided, mark it as 'Not verified'. Return ONLY valid JSON when asked."
)


def _key() -> str:
    return os.environ.get("EMERGENT_LLM_KEY", "")


def _chat(session_id: str) -> LlmChat:
    return LlmChat(
        api_key=_key(),
        session_id=session_id,
        system_message=SYSTEM_PROMPT,
    ).with_model(MODEL_PROVIDER, MODEL_NAME)


async def _ask_json(session_id: str, prompt: str) -> dict:
    chat = _chat(session_id)
    resp = await chat.send_message(UserMessage(text=prompt))
    text = resp.strip()
    if text.startswith("```"):
        text = text.split("```", 2)[1]
        if text.startswith("json"):
            text = text[4:]
    text = text.strip().strip("`").strip()
    start, end = text.find("{"), text.rfind("}")
    if start != -1 and end != -1:
        text = text[start:end + 1]
    return json.loads(text)


async def _ask_text(session_id: str, prompt: str) -> str:
    chat = _chat(session_id)
    resp = await chat.send_message(UserMessage(text=prompt))
    return resp.strip()


def _fallback_report(lead: dict) -> dict:
    name = lead.get("business_name", "This business")
    weak = (lead.get("website_status") or "").lower() in ("missing", "weak", "unknown")
    return {
        "generated_by": "heuristic-fallback",
        "business_overview": f"{name} is a {lead.get('category','business')} operating in {lead.get('location','its local market')}.",
        "digital_presence": "Assessed from provided public signals only. Not verified.",
        "website_assessment": "No dedicated website found." if weak else "A website exists; conversion quality not verified.",
        "social_presence": "Public social profiles referenced where available. Not verified.",
        "business_signals": "Active local demand inferred from category and location.",
        "pain_points": ["Limited online discoverability", "Manual enquiry handling", "No structured lead capture"],
        "software_opportunity": "Conversion-focused website plus enquiry automation.",
        "recommended_solution": lead.get("project_type") or "Website + WhatsApp enquiry automation",
        "project_category": "Small Business Web + Automation",
        "lead_score": lead.get("lead_score", 70),
        "conversion_potential": lead.get("conversion_score", "MEDIUM"),
        "outreach_channel": "WhatsApp",
        "personalized_pitch": f"Hi {name}, we help {lead.get('category','businesses')} in {lead.get('location','your area')} turn online interest into booked customers with a fast website and automated WhatsApp enquiries.",
        "follow_up": "Follow up in 3 days if no reply; share a 1-page mockup on the second touch.",
        "why": "Assessment generated by local heuristics (LLM unavailable at request time).",
    }


async def research_lead(lead: dict) -> dict:
    """Produce the 14-section AI research report for a lead."""
    prompt = f"""Analyze this prospect for Virtelon and return a JSON research report.

PROSPECT (public info only; treat blanks as unknown):
{json.dumps(lead, default=str)}

Return ONLY a JSON object with EXACTLY these keys:
- business_overview (string)
- digital_presence (string)
- website_assessment (string)
- social_presence (string)
- business_signals (string)
- pain_points (array of 3-5 short strings)
- software_opportunity (string)
- recommended_solution (string, a concrete Virtelon offering)
- project_category (string)
- lead_score (integer 0-100)
- conversion_potential (string: HIGH, MEDIUM or LOW)
- outreach_channel (string: WhatsApp, Email or LinkedIn)
- personalized_pitch (string, 2-3 sentences, specific, not spammy)
- follow_up (string, a concrete follow-up recommendation)
- why (string, explain the reasoning behind the assessment)

Rules: never invent contact details. If a factual claim cannot be verified from the provided data, hedge with 'likely' or note 'Not verified'."""
    try:
        data = await _ask_json(f"research-{lead.get('id','x')}", prompt)
        data.setdefault("generated_by", MODEL_NAME)
        return data
    except Exception as e:
        logger.warning(f"research_lead fallback: {e}")
        return _fallback_report(lead)


async def score_lead(lead: dict) -> dict:
    prompt = f"""Score this prospect for software-services conversion potential.
PROSPECT: {json.dumps(lead, default=str)}
Return ONLY JSON: {{"lead_score": int 0-100, "conversion_score": "HIGH|MEDIUM|LOW", "digital_presence_score": int 0-100, "reason": "one sentence"}}"""
    try:
        return await _ask_json(f"score-{lead.get('id','x')}", prompt)
    except Exception as e:
        logger.warning(f"score_lead fallback: {e}")
        return {
            "lead_score": lead.get("lead_score", 70),
            "conversion_score": lead.get("conversion_score", "MEDIUM"),
            "digital_presence_score": lead.get("digital_presence_score", 50),
            "reason": "Heuristic score (LLM unavailable).",
        }


CHANNEL_GUIDE = {
    "whatsapp": "a short, warm WhatsApp message (max 6 lines), friendly and specific, one clear CTA",
    "email": "a concise professional email with a subject line on the first line prefixed 'Subject:', then body, max 12 lines",
    "linkedin": "a professional LinkedIn connection/opening message, max 5 lines, no hard selling",
}


async def generate_pitch(lead: dict, research: dict, channel: str = "whatsapp") -> str:
    guide = CHANNEL_GUIDE.get(channel, CHANNEL_GUIDE["whatsapp"])
    prompt = f"""Write {guide} from Virtelon (a software agency) to this prospect.
Use the research to make it specific and personalized. Do NOT be spammy or generic.
Reference their actual situation. Sign off as 'Team Virtelon'.

PROSPECT: {json.dumps({k: lead.get(k) for k in ['business_name','category','location','website_status']}, default=str)}
RESEARCH: {json.dumps({k: research.get(k) for k in ['recommended_solution','pain_points','software_opportunity','personalized_pitch']}, default=str)}

Return ONLY the message text, no preamble."""
    try:
        return await _ask_text(f"pitch-{channel}-{lead.get('id','x')}", prompt)
    except Exception as e:
        logger.warning(f"generate_pitch fallback: {e}")
        base = research.get("personalized_pitch") or _fallback_report(lead)["personalized_pitch"]
        return f"{base}\n\nWould love to show you a quick example. Open to a short chat this week?\n\n— Team Virtelon"


async def generate_followup(lead: dict, research: dict) -> str:
    prompt = f"""Write a short, polite follow-up message (max 5 lines) from Virtelon to a prospect who has not yet replied.
Add value, no pressure, one soft CTA. Sign off 'Team Virtelon'.
PROSPECT: {lead.get('business_name')} ({lead.get('category')}, {lead.get('location')})
CONTEXT: {research.get('recommended_solution','')}
Return ONLY the message text."""
    try:
        return await _ask_text(f"followup-{lead.get('id','x')}", prompt)
    except Exception as e:
        logger.warning(f"generate_followup fallback: {e}")
        return f"Hi again from Virtelon — just floating this back to the top of your inbox. Happy to share a quick mockup for {lead.get('business_name','your business')} whenever you have 2 minutes.\n\n— Team Virtelon"
